"""
Test file generator.

Creates test files (PDF, Markdown, etc.) for API testing.
"""

import os
import tempfile
from pathlib import Path
from typing import Optional


class TestFileGenerator:
    """Generate test files for API testing."""
    
    # Test files directory
    TEST_FILES_DIR = Path(__file__).parent / "test_files"
    
    @classmethod
    def ensure_test_dir(cls):
        """Ensure test files directory exists."""
        cls.TEST_FILES_DIR.mkdir(exist_ok=True)
    
    @classmethod
    def create_markdown_file(cls, filename: str = "test_blog.md", 
                             title: str = "Test Blog Post",
                             content: Optional[str] = None) -> Path:
        """
        Create a test markdown file.
        
        Args:
            filename: File name
            title: Blog title
            content: Blog content (optional)
            
        Returns:
            Path to created file
        """
        cls.ensure_test_dir()
        
        if content is None:
            content = f"""# {title}

This is a test blog post created by the API test suite.

## Introduction

This content is automatically generated for testing purposes.

## Test Content

Here are some test sections:

### Section 1
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

### Section 2
Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

## Conclusion

This test file validates the blog upload functionality.

---
*Generated by TestFileGenerator*
"""
        
        file_path = cls.TEST_FILES_DIR / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return file_path
    
    @classmethod
    def create_pdf_file(cls, filename: str = "test_book.pdf") -> Path:
        """
        Create a simple test PDF file.
        
        Note: This creates a minimal valid PDF for testing.
        
        Args:
            filename: File name
            
        Returns:
            Path to created file
        """
        cls.ensure_test_dir()
        
        # Minimal valid PDF content
        pdf_content = b"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>
endobj
4 0 obj
<< /Length 44 >>
stream
BT
/F1 12 Tf
100 700 Td
(Test Book for API Testing) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000214 00000 n 
0000000307 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
385
%%EOF
"""
        
        file_path = cls.TEST_FILES_DIR / filename
        with open(file_path, 'wb') as f:
            f.write(pdf_content)
        
        return file_path
    
    @classmethod
    def get_existing_markdown_file(cls) -> Optional[Path]:
        """Get an existing markdown file from test_files directory."""
        cls.ensure_test_dir()
        
        # Look for existing markdown files
        md_files = list(cls.TEST_FILES_DIR.glob("*.md"))
        if md_files:
            return md_files[0]
        
        # Create one if none exists
        return cls.create_markdown_file()
    
    @classmethod
    def get_existing_pdf_file(cls) -> Optional[Path]:
        """Get an existing PDF file from test_files directory."""
        cls.ensure_test_dir()
        
        # Look for existing PDF files
        pdf_files = list(cls.TEST_FILES_DIR.glob("*.pdf"))
        if pdf_files:
            return pdf_files[0]
        
        # Create one if none exists
        return cls.create_pdf_file()
    
    @classmethod
    def cleanup(cls):
        """Remove all test files."""
        if cls.TEST_FILES_DIR.exists():
            for file in cls.TEST_FILES_DIR.iterdir():
                file.unlink()
            cls.TEST_FILES_DIR.rmdir()
